language: node_js
after_success:
    - if [[ $TRAVIS_BRANCH = "master" ]]; then ./deploy.sh --verbose; fi
env:
    global:
        - secure: "SWODHgKAZQXbhPX0nyGyOUjolSrvptBhkmqrthX4A7cbmPWEFGEHQfDmLAeoe4nHDnKttBGqJO7XrzxYIRFcsBTlgbEckLQveNv7DddTUsjgbkKcP/VTD8SpW9X+N7pqAbZYcXX6vU/KiDDPEzcmHcTm1cAcim0nYMWYUHAE8GQ="
