language: node_js
after_success:
    - ./deploy.sh --verbose
env:
    global:
        - secure: "SWODHgKAZQXbhPX0nyGyOUjolSrvptBhkmqrthX4A7cbmPWEFGEHQfDmLAeoe4nHDnKttBGqJO7XrzxYIRFcsBTlgbEckLQveNv7DddTUsjgbkKcP/VTD8SpW9X+N7pqAbZYcXX6vU/KiDDPEzcmHcTm1cAcim0nYMWYUHAE8GQ="
